### ISSUE TITLE
Aaron is sick

### ISSUE THREAD

**Issue by aaronpk** [onewheelskyward/NSBrunch#5]
I got food poisoning Thursday night, and have been in bed all day Friday. I'm hoping it's a 24-hour thing, but I have no idea. I may wake up tomorrow and feel fine or not. As such, you should not count on me being there tomorrow. :( Hope you have fun though!

**Comment by incanus** [comment]
Ugh, feel better. I've been sick, too. SUCKS. 

## 

Justin R. Miller
http://codesorcery.net

**Comment by onewheelskyward** [comment]
Sorry we missed you!  Next time.
