### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by incanus** [onewheelskyward/NSBrunch#7]
We should consider releasing v2.0. 

@onewheelskyward @castirony @bsneed @samgrover @janineanne @aaronpk

**Comment by onewheelskyward** [comment]
Was that a hosting offer I heard?  :)  Actually I could do it.  If you guys don't mind a day's travel.

**Comment by janineanne** [comment]
We could host at some point too - we are even farther out, but at least the Max runs almost to our front door.

janine

**Comment by incanus** [comment]
Joel and I were talking last night and would both be open to hosting. Is he on GitHub? @castirony doesn't work and he's not `@joelbernstein`.

**Comment by samgrover** [comment]
He is @Bergamot

**Comment by onewheelskyward** [comment]
Must be a tea drinker.

**Comment by incanus** [comment]
Well that was obvious.

**Comment by incanus** [comment]
Ok folks let's get this started. I'm happy to host. Good candidates are: 
- Feb 9
- Feb 22-23
- Mar 1-2
- Mar 8-9

Who'd be in?

**Comment by janineanne** [comment]
We're in. As far as I know all those dates work for us at the moment. 

janine

**Comment by incanus** [comment]
Ok, let's try this again. Some weekends that work for me hosting: 
- May 17-18
- May 24-25
- May 31-June 1

Also adding @schlu to the mix. Anyone else have GitHub handles we should add?

**Comment by CastIrony** [comment]
I'm free for all of those.

**Comment by janineanne** [comment]
The last one is best for Wayne and I.  The first weekend we'll be in Medford for a dance event, and the middle one is my birthday weekend.  Not that I mind spending my birthday with y'all, but we might have other things going on. :)

janine

**Comment by samgrover** [comment]
All of those work for me as well.

**Comment by incanus** [comment]
Gah, so hard to get this going. Bump again. I think the weekend of June 1 is out (sorry @janineanne) since WWDC starts up right after and I will probably already be in SF. 

So back down to these two; which work? 
- May 17-18
- May 24-25

**Comment by CastIrony** [comment]
I’m free for both of those.

-Joel

**Comment by onewheelskyward** [comment]
I will be in New Mexico on the 17-18.

**Comment by samgrover** [comment]
I can do either.

**Comment by janineanne** [comment]
We probably can't do either, but the second weekend is slightly more possible than the first, when we will be out of town.

janine

**Comment by incanus** [comment]
Cool, let's get it on the board for May 24-25 then. Sunday May 25? 11am?

**Comment by janineanne** [comment]
Since no-one else has replied yet, can I make a request for Saturday?  The weekend we're talking about is my birthday weekend and I think there's going to be a picnic on Sunday, which some of you will be invited to (maybe all, I don't know who all is on this list).  I doubt anyone's going to want to go to brunch and a picnic on the same day.

I'm not sure exactly what the festivities will be because Wayne is supposed to be planning it, which is why no-one knows about it yet... :)  

janine

**Comment by samgrover** [comment]
Sounds good!

**Comment by incanus** [comment]
Saturday works for me. Still 11am?

**Comment by samgrover** [comment]
Sounds good!

**Comment by janineanne** [comment]
So it turns out that plans have changed and we're not having a picnic, or any sort of organized party at all - we're going somewhere for the weekend (I don't know where, it's a surprise :).  So feel free to have brunch on Sunday if you would like, but thanks to all for being willing to accommodate my request!

Hopefully we'll be able to attend the next one.

janine

**Comment by incanus** [comment]
Ok. I'd prefer Sunday then. Let's go back to Sunday May 25, 11am. I'll start a milestone.

**Comment by incanus** [comment]
Oh. @onewheelskyward will have to do this. Create a `2.0`? Then we can make tickets for all the things we need to bring.

**Comment by onewheelskyward** [comment]
Milestone created.

**Comment by samgrover** [comment]
Hmmm... I have no idea how this milestone thing works. I brought bacon last time. I can bring bacon again!

**Comment by incanus** [comment]
I was gonna make tickets for what we need, put 'em in the milestone, and assign them!

**Comment by incanus** [comment]
Ok, I can't assign tickets to milestones in @onewheelskyward's repository. It's dawning on me that maybe GitHub isn't the best event planning tool. 

Let's just do a list. 
- [ ] bacon - @samgrover 
- [ ] coffee - @incanus
- [ ] donuts
- [ ] pancakes or waffles
- [ ] ???

**Comment by onewheelskyward** [comment]
LOL!

On Wed, May 14, 2014 at 10:13 AM, Justin R. Miller <notifications@github.com

**Comment by onewheelskyward** [comment]
I added you as a collaborator, @incanus, try now?

**Comment by onewheelskyward** [comment]
Also, assign pancakes to me.

**Comment by incanus** [comment]
Ok now I can do the milestone thing. Moving to tickets for things.
